# Generated by Django 6.0.1 on 2026-01-26 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='audio_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
