# Generated by Django 6.0.1 on 2026-01-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_alter_lesson_audio_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='raw_llm_output',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
